# Generated by Django 6.0 on 2026-02-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_f',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='food')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
