# Generated by Django 6.0 on 2026-02-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0002_menu_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='span',
            field=models.CharField(max_length=1000),
        ),
    ]
