# Generated by Django 6.0 on 2025-12-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0003_alter_images_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='Name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='Products'),
        ),
    ]
