# Generated by Django 6.0 on 2025-12-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0004_alter_images_name_alter_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Menu')),
                ('price', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='Name',
            new_name='name',
        ),
    ]
