# Generated by Django 6.0 on 2025-12-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0005_food_delete_product_rename_name_images_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='Image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='food',
            name='Name',
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='text',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(default='Item', max_length=100),
        ),
    ]
