# Generated by Django 6.0 on 2025-12-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0006_rename_image_food_image_remove_food_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
    ]
