# Generated by Django 6.0 on 2025-12-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0007_food_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('message', models.TextField()),
            ],
        ),
    ]
