# Generated by Django 6.0 on 2025-12-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0008_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
