# Generated by Django 6.0 on 2025-12-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0009_alter_contactform_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='down',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Images')),
                ('name', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('text', models.TextField()),
            ],
        ),
    ]
