# Generated by Django 6.0 on 2025-12-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0010_down'),
    ]

    operations = [
        migrations.AlterField(
            model_name='down',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
