# Generated by Django 6.0 on 2026-01-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0011_alter_down_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='down',
            name='image',
            field=models.ImageField(upload_to='downs'),
        ),
    ]
