# Generated by Django 6.0 on 2026-01-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0012_alter_down_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='down',
            name='head',
            field=models.CharField(default='Item', max_length=50),
        ),
    ]
