# Generated by Django 6.0 on 2026-01-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0013_down_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Blog')),
                ('date', models.DateField()),
                ('head', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('span', models.CharField(max_length=100)),
            ],
        ),
    ]
