# Generated by Django 6.0 on 2026-01-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0015_alter_blog_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Our')),
                ('date', models.DateField()),
                ('head', models.CharField(max_length=50)),
                ('span', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=50)),
            ],
        ),
    ]
