# Generated by Django 6.0 on 2026-01-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0016_our'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
