# Generated by Django 6.0 on 2026-01-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0017_alter_our_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('hour', models.DateTimeField()),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('person', models.CharField(max_length=10)),
            ],
        ),
    ]
