# Generated by Django 6.0 on 2026-01-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0018_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='hour',
            field=models.DateField(),
        ),
    ]
