# Generated by Django 6.0 on 2026-01-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0019_alter_registration_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='hour',
            field=models.CharField(),
        ),
    ]
