# Generated by Django 6.0 on 2026-01-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0020_alter_registration_hour'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Book',
        ),
    ]
