# Generated by Django 6.0 on 2026-01-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0022_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, null=True)),
                ('password', models.CharField(max_length=8, null=True)),
            ],
        ),
    ]
