# Generated by Django 6.0 on 2026-01-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0023_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
            ],
        ),
    ]
