# Generated by Django 6.0 on 2026-01-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0024_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='order_status',
        ),
    ]
