# Generated by Django 6.0 on 2026-01-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0025_rename_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('total', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_done', models.BooleanField(default=False)),
            ],
        ),
    ]
