# Generated by Django 6.0 on 2026-01-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0026_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='food/')),
                ('description', models.TextField()),
            ],
        ),
    ]
