# Generated by Django 6.0 on 2026-01-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0029_remove_orderitem_item_remove_order_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('address', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
