# Generated by Django 6.0 on 2026-01-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0030_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default='name', max_length=30),
        ),
    ]
