# Generated by Django 6.0 on 2026-01-19 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0031_alter_book_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victory.food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victory.order')),
            ],
        ),
    ]
