# Generated by Django 6.0 on 2026-01-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0032_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=25)),
                ('amount', models.CharField(max_length=5)),
                ('message', models.TextField()),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
