# Generated by Django 6.0 on 2026-01-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0033_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
