# Generated by Django 6.0 on 2026-01-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0034_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='modelselection',
            field=models.CharField(default=False, max_length=20),
            preserve_default=False,
        ),
    ]
