# Generated by Django 6.0 on 2026-01-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0035_payment_modelselection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
