# Generated by Django 6.0 on 2026-01-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0040_rename_razorpay_payment_id_payment_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, default=1, max_length=100),
        ),
    ]
