# Generated by Django 6.0 on 2026-01-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0041_alter_payment_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Menu'),
        ),
        migrations.AlterField(
            model_name='food',
            name='text',
            field=models.TextField(),
        ),
    ]
