# Generated by Django 6.0 on 2026-01-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0044_remove_payment_order_remove_food_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
