# Generated by Django 6.0 on 2026-01-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0046_remove_food_text_remove_order_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.CharField(),
        ),
    ]
