# Generated by Django 6.0 on 2026-01-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victory', '0054_alter_food_image_alter_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
