# Generated by Django 6.0 on 2026-06-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("victory", "0003_alter_blog_span"),
        ("victory", "0055_remove_food_image_order_is_paid"),
    ]

    operations = []
